### PR TITLE
Update style.css

### PR DESCRIPTION
**Pull request by KoblaQ**
Fix [AB#12](https://dev.azure.com/LosL0b0s-DevOps/a9d70c35-d483-461d-acec-3f50b5df19fb/_workitems/edit/12)

### CODE REVIEW

**Review by Fernoss — COMMENTED** [review]
The website looks nice!

**Review by Fernoss — DISMISSED** [review]
Can you specify what changes you did on style.css file?

**Review by Fernoss — CHANGES_REQUESTED** [review]
Can you change the padding on h3's

**Review by KoblaQ — COMMENTED** [review]
It is done.

**Review by Fernoss — APPROVED** [review]
Good job!

**Pull request merged**
