### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by Fernoss**
fix [AB#16](https://dev.azure.com/LosL0b0s-DevOps/a9d70c35-d483-461d-acec-3f50b5df19fb/_workitems/edit/16)

### CODE REVIEW

**Review by KoblaQ — COMMENTED** [review]
Good work. Much better than previous.

**Review by KoblaQ — CHANGES_REQUESTED** [review]
Change everything.

**Review by Fernoss — COMMENTED** [review]
It's done!

**Review by KoblaQ — APPROVED** [review]
approved

**Pull request merged**
